name: subly_application
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  device_preview: ^1.1.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
